# Generated by Django 3.2 on 2024-05-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('name_code', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('TRY', 'TRY'), ('INR', 'INR'), ('CNY', 'CNY')], max_length=3)),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('date', 'name_code')},
            },
        ),
    ]
