# Generated by Django 4.2.13 on 2024-05-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_basecurrency_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecurrency',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='basecurrency',
            unique_together={('date', 'name_code')},
        ),
    ]
