# Generated by Django 4.2.13 on 2024-05-16 13:00

import computedfields.resolver
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_basecurrency_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('difference', models.FloatField(editable=False)),
                ('name_code', models.FloatField(editable=False)),
                ('base_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.basecurrency')),
                ('date_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
            ],
            options={
                'unique_together': {('date', 'date_currency')},
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
    ]
