# Generated by Django 4.2.13 on 2024-05-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_currencychanges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecurrency',
            name='name_code',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('TRY', 'TRY'), ('INR', 'INR'), ('CNY', 'CNY')], max_length=3, unique=True),
        ),
    ]
