# Generated by Django 4.2.13 on 2024-05-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_alter_basecurrency_name_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencychanges',
            name='name_code',
            field=models.CharField(editable=False, max_length=3),
        ),
    ]
