# Generated by Django 4.2.13 on 2024-05-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_alter_currencychanges_name_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecurrency',
            options={'verbose_name': 'base_currency'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'currency'},
        ),
        migrations.AlterField(
            model_name='basecurrency',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='basecurrency',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='basecurrency',
            name='name_code',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('TRY', 'TRY'), ('INR', 'INR'), ('CNY', 'CNY')], max_length=3, unique=True, verbose_name='name_code'),
        ),
        migrations.AlterField(
            model_name='basecurrency',
            name='value',
            field=models.FloatField(verbose_name='currency value'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name_code',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('TRY', 'TRY'), ('INR', 'INR'), ('CNY', 'CNY')], max_length=3, verbose_name='name code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='value',
            field=models.FloatField(verbose_name='currency value'),
        ),
        migrations.AlterField(
            model_name='currencychanges',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='currencychanges',
            name='difference',
            field=models.FloatField(editable=False, verbose_name='difference'),
        ),
        migrations.AlterField(
            model_name='currencychanges',
            name='name_code',
            field=models.CharField(editable=False, max_length=3, verbose_name='name code'),
        ),
    ]
